### ISSUE TITLE
私のvimはあなたのスクリーンショットとは違って見えます。 `.vimrc`のアップデートはありますか？

### ISSUE THREAD

**Issue by u3u** [yui540/hyper-akari#3]
また、 [hyper-statusline](https://github.com/henrikdahl/hyper-statusline) と [hyper-tabs-enhanced](https://github.com/henrikdahl/hyper-tabs-enhanced) プラグインのスタイルを最適化できますか？

![image](https://user-images.githubusercontent.com/20062482/42407523-ad9035e4-81f0-11e8-8d85-05e255cfbe1e.png)

私はこれらの2つのプラグインを使用した後、私の端末はこのように見えます。

**Comment by yui540** [comment]
プラグイン同士でスタイルが衝突し合ってるので、hyper-statusline, hyper-tabs-enhancedのソースコードを読んでから、スタイルを修正していくのでしばらくお待ちください🙏

**Comment by u3u** [comment]
どうもありがとうございます。まず [.dotfiles](https://github.com/yui540/.dotfiles) を更新できますか？🙏

**Comment by yui540** [comment]
.dotfilesの更新はもうちょっと待ってね🙏🙏🙏
