### ISSUE TITLE
黒や他の色のコントラストは明白ではない

### ISSUE THREAD

**Issue by u3u** [yui540/hyper-akari#5]
![image](https://user-images.githubusercontent.com/20062482/42417243-d0743dcc-82b7-11e8-8fde-3cf2cb56f903.png)

`src/colors/index.js` の `black` 属性を `#000000` の効果に変更しました：

![image](https://user-images.githubusercontent.com/20062482/42417251-19b34564-82b8-11e8-99f3-734a0955f5b8.png)

**Comment by yui540** [comment]
私の環境だと、black属性を変更すると別のところで問題が起こるので、解決策を探ってみます🙏

**Comment by pandanoir** [comment]
これと同様の問題がtmuxでも起きました。

![screenshot from 2018-07-10 10-26-18](https://user-images.githubusercontent.com/2884499/42484073-104bf0b4-842c-11e8-9df0-d4e3698021cd.png)

![screenshot from 2018-07-10 10-26-35](https://user-images.githubusercontent.com/2884499/42484075-135f2cee-842c-11e8-9e84-b65d58f0256e.png)

**Comment by Cj-bc** [comment]
`less`でも同様の問題を確認しました。
他の人のcolor themeでも同様な問題が起きているようですね。（知り合いが困ってた）
他の人のおっしゃっている解決方法は、試せていません（JS慣れてないのと、`black`記述が数カ所あるのでわからなかった）
何か解決方法があると良いのですが...
<img width="1439" alt="2018-11-17 22 41 25" src="https://user-images.githubusercontent.com/16875061/48661759-9f2ad080-eaba-11e8-9e0c-bd4c5702f14d.png">

**Comment by yui540** [comment]
対応が遅くなってしまい、申し訳ないです🙏

![image](https://user-images.githubusercontent.com/12015279/48820290-bbb75900-ed97-11e8-9dd4-b7235a4c6054.png)
![image](https://user-images.githubusercontent.com/12015279/48820292-bf4ae000-ed97-11e8-9345-f129031e2b6e.png)

macOS限定の背景ブラー等の機能を問題の修正のために消去しましたが、一応、色の周り問題を解決できるように修正しました。
また、別の問題が見つかった場合はおしらせください🙏

**Comment by Cj-bc** [comment]
ありがとうございます！！
